name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: kotlinc Kotlin.kt -include-runtime -d Kotlin.jar; java -jar Kotlin.jar
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: Kotlin.jar
        
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Make all
      run: make all
    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["./bin/release-it*"]'
