name: release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: kotlinc Kotlin.kt -include-runtime -d Kotlin.jar; java -jar Kotlin.jar
    
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: Kotlin.jar

    - uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: xz
        GHR_PATH: build/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
