name: release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: kotlinc Kotlin.kt -include-runtime -d Kotlin.jar; java -jar Kotlin.jar
    
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: Kotlin.jar
        
    - uses: jasondavis303/tag-and-release-and-upload@v1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
          
        # Use the version from the previous step
        version: v${{ steps.get_version.outputs.ASSEMBLY_VERSION }}
          
        assets: '[ "binaries.zip", "otherstuff.zip" ]'
        overwrite: false   
